jobs:
  Generate-Docs:
    steps:
      - name: Install Docs Requirements
        run: python -m pip install --upgrade -r docs/requirements.txt
      - name: Install newer versions scikit learn scipy
        run: pip install --upgrade scipy scikit-learn
      - name: Install newer version of sphinx-gallery
        run: pip install -U https://api.github.com/repos/sphinx-gallery/sphinx-gallery/zipball/master
      - name: Create Docs
        run: |
          cd docs
          make html
      - name: Upload HTML Docs as Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: HTML-Docs
          path: ./docs/_build/
      - name: Deploy to Github Pages if on Master
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && matrix.skorch_version == 'stable'}}
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: braindecode/braindecode.github.io
          destination_dir: dev
          publish_branch: master
          publish_dir: ./docs/_build/html
          cname: braindecode.org
