name: tests-and-docs

on:
  pull_request:
  push:
    branches: master

jobs:
  Install-Test-Doc-Braindecode:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
        python-version: [ 3.7, 3.8, 3.9, 3.10, 3.11 ]
        skorch_version: ['main', 'stable']
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: install.yml
    - uses: test.yml
    - uses: docs.yml
